version: '3'

services:
  tbb-deploy-nginx:
    container_name: tbb-prod-nginx
    build: nginx
    image: tbb-image-nginx
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 3001:3001
    depends_on:
      - tbb-prod-beego
      # - tbb-prod-fe
  tbb-prod-beego:
    build: tre-booking-be
    container_name: tbb-prod-be
    image: tbb-image-beego
    volumes:
      - ./tre-booking-be/server:/go/src/beego
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    working_dir: /go/src/beego
    command: sh -c "go mod tidy && bee generate routers && bee run"
    # docker exec -it tre-booking-beego bash -c "go mod tidy && bee run"
    # docker exec -it tre-booking-beego golangci-lint run
    restart: unless-stopped
    tty: true
  mongodb:
    image: mongo:6.0.3
    container_name: tbb-prod-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=c6MV5hvJebRn7KXa
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    tty: true
    # run following command to interact with server mongodb: docker exec -it tre-booking-mongodb mongosh
  tbb-prod-fe:
    build: tre-booking-fe
    container_name: tbb-prod-fe
    ports:
      - '3000:3000'

volumes:
  db:
    name: mongodb
